version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: gm_database
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - ./tmp/pg:/var/lib/gm-database/postgres/data
    env_file:
      - docker.env
    networks:
      - postgres

  adminer:
    image: adminer
    container_name: pg_adminer_gm_db
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./tmp/pgadmin:/var/lib/gm-database/pgadmin/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

  minio:
    image: minio/minio
    volumes:
      - ./tmp/s3/data:/data
    restart: always
    ports:
      - '9000:9000'
      - '9001:9001'
    env_file:
      - docker.env
    command: server /data --console-address ":9001"

networks:
  postgres:
    driver: bridge

