version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: gm_database
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - ./tmp/pg:/var/lib/gm-database/postgres/data
    env_file:
      - docker.env
    networks:
      - postgres

  adminer:
    image: adminer
    container_name: pg_adminer_gm_db
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./tmp/pgadmin:/var/lib/gm-database/pgadmin/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

  minio1:
    image: minio/minio:RELEASE.2020-08-08T04-50-06Z
    volumes:
      - ./tmp/s3/data1-1:/data1
      - ./tmp/s3/data1-2:/data2
    ports:
      - '9001:9000'
    env_file:
      - docker.env
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

  minio2:
    image: minio/minio:RELEASE.2020-08-08T04-50-06Z
    volumes:
      - ./tmp/s3/data2-1:/data1
      - ./tmp/s3/data2-2:/data2
    ports:
      - '9002:9000'
    env_file:
      - docker.env
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

  minio3:
    image: minio/minio:RELEASE.2020-08-08T04-50-06Z
    volumes:
      - ./tmp/s3/data3-1:/data1
      - ./tmp/s3/data3-2:/data2
    ports:
      - '9003:9000'
    env_file:
      - docker.env
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

  minio4:
    image: minio/minio:RELEASE.2020-08-08T04-50-06Z
    volumes:
      - ./tmp/s3/data4-1:/data1
      - ./tmp/s3/data4-2:/data2
    ports:
      - '9004:9000'
    env_file:
      - docker.env
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  postgres:
    driver: bridge

